FROM debian:jessie
# build-dependencies for LibreS3
# opam: not strictly required, but allows building dependencies separately
# aspcud: ensures opam provides an optimal install solution
# ocaml-native-compilers : ensure native ocamlopt is used (faster builds)
RUN apt-get update && apt-get install --no-install-recommends -y\
        git gcc make libc-dev\
        opam aspcud ocaml-native-compilers && apt-get clean
RUN useradd -m build -g staff
USER build
WORKDIR /home/build
ENV OPAMJOBS 9
RUN opam init -y
RUN (opam install -e debian libres3; echo libpcre3-dev camlp4-extra) >packages

# could be simplified if we'd use root for building
USER root
RUN apt-get install --no-install-recommends -y `cat packages` && apt-get clean

USER build
RUN opam install -y --deps-only libres3

RUN git clone @LIBRES3_URL@

# install extra packages needed for tests
RUN opam install ounit

USER root
RUN apt-get install -y --no-install-recommends s3cmd python-boto uuid-runtime && apt-get clean

USER build
WORKDIR /home/build/libres3/libres3
RUN git remote update && git checkout @LIBRES3_REV@ && eval `opam config env` &&\
        ./configure --disable-docs --enable-tests --override ocamlbuildflags '-j 0'\
        && make test install

EXPOSE 8443
